version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
